const STORAGE_KEY='chawchaosamut-competitor-intelligence-v1';
const sampleCompetitors=[
 {id:'c1',brand:'ทาโร',product:'ปลาสวรรค์ รสเข้มข้น',channel:'Big C',type:'หมวดเดียวกัน',weight:30,normalPrice:30,promoPrice:0,packScore:5,productScore:4,diffScore:4,shelf:'ออนไลน์',sellingPoint:'แบรนด์ใหญ่ ราคาเข้าใจง่าย',note:'รูปแบบเป็นปลาเส้นทั่วไป',url:''},
 {id:'c2',brand:'เบนโตะ',product:'หมึกบด เจแปนนีสซอยซอส',channel:'Big C',type:'หมวดเดียวกัน',weight:18,normalPrice:20,promoPrice:0,packScore:5,productScore:4,diffScore:4,shelf:'ออนไลน์',sellingPoint:'รสเข้มข้น แบรนด์เป็นที่รู้จัก',note:'ไม่ใช่ปลาหวานโดยตรง',url:''},
 {id:'c3',brand:'ตราเรือ',product:'ปลาหวานแผ่นปรุงรส',channel:'All Online',type:'คู่แข่งตรง',weight:120,normalPrice:37.33,promoPrice:0,packScore:3,productScore:4,diffScore:3,shelf:'ออนไลน์',sellingPoint:'ปลาหวานตรงหมวด ราคาต่อกรัมต่ำ',note:'แพ็กค่อนข้างดั้งเดิม',url:''},
 {id:'c4',brand:'เท็นจัง',product:'ปลาแผ่นรสเผ็ดแซ่บ',channel:'All Online',type:'หมวดเดียวกัน',weight:35,normalPrice:60,promoPrice:45,packScore:4,productScore:4,diffScore:4,shelf:'ออนไลน์',sellingPoint:'รสชาติชัด แพ็กทันสมัย',note:'ราคาปกติค่อนข้างสูง',url:''},
 {id:'c5',brand:'ริชโช่',product:'ปลาเส้นรสเข้มข้น',channel:'All Online',type:'หมวดเดียวกัน',weight:170,normalPrice:69,promoPrice:0,packScore:3,productScore:4,diffScore:3,shelf:'ออนไลน์',sellingPoint:'แพ็กใหญ่ ราคาต่อกรัมต่ำ',note:'ไม่เหมาะกับการซื้อทดลอง',url:''},
 {id:'c6',brand:'เบนโตะ',product:'ปลาเส้นบาร์บีคิวทรงเครื่อง',channel:'Big C',type:'หมวดเดียวกัน',weight:15,normalPrice:10,promoPrice:5,packScore:4,productScore:3,diffScore:3,shelf:'ออนไลน์',sellingPoint:'จุดราคาทดลองต่ำมาก',note:'ราคาโปรโมชั่นอาจบิดเบือนตลาด',url:''}
];
const defaultPricing={productWeight:40,rawCost:5.5,packCost:2,laborCost:1,logisticsCost:.8,overheadCost:.4,wastePct:2,promoPct:8,retailerMarginPct:30,vatPct:7,targetGmPct:35,positionPct:0};
let state=loadState(); let editingId=null;
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(x&&Array.isArray(x.competitors))return {...x,pricing:{...defaultPricing,...x.pricing}}}catch(e){}return {competitors:sampleCompetitors,pricing:{...defaultPricing}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
const money=n=>'฿'+Number(n||0).toLocaleString('th-TH',{maximumFractionDigits:2,minimumFractionDigits:Number(n)%1?2:0});
const num=n=>Number(n)||0; const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function usedPrice(c){return num(c.promoPrice)>0?num(c.promoPrice):num(c.normalPrice)}
function ppg(c){return c.weight?usedPrice(c)/num(c.weight):0}
function normalized(c,w=state.pricing.productWeight){return ppg(c)*num(w)}
function avg(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:0}
function median(arr){if(!arr.length)return 0;const s=[...arr].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
function priceLadder(v){const ladder=[15,20,25,29,30,35,39,40,45,49,50,59,69,79,89,99,119,129,149,169,199,249,299];return ladder.find(x=>x>=v)||Math.ceil((v+1)/10)*10-1}
function calcPricing(positionOverride=null,retailOverride=null){const p=state.pricing,w=clamp(num(p.wastePct)/100,0,.95),promo=clamp(num(p.promoPct)/100,0,.95),rm=clamp(num(p.retailerMarginPct)/100,0,.95),vat=num(p.vatPct)/100,gm=clamp(num(p.targetGmPct)/100,0,.95);const direct=num(p.rawCost)+num(p.packCost)+num(p.laborCost)+num(p.logisticsCost)+num(p.overheadCost);const cost=direct/(1-w);const netNeeded=cost/(1-gm);const wholesaleNeeded=netNeeded/(1-promo);const floorRetail=wholesaleNeeded/(1-rm)*(1+vat);const competitors=state.competitors.filter(c=>c.weight&&usedPrice(c)>0);const marketPpg=avg(competitors.map(ppg));const benchmark=marketPpg*num(p.productWeight);const position=(positionOverride===null?num(p.positionPct):positionOverride)/100;const marketTarget=benchmark*(1+position);const rawRecommended=Math.max(floorRetail,marketTarget);const recommended=retailOverride||priceLadder(rawRecommended);const wholesale=recommended/(1+vat)*(1-rm);const netRevenue=wholesale*(1-promo);const profit=netRevenue-cost;const actualGm=netRevenue?profit/netRevenue:0;return {direct,cost,netNeeded,wholesaleNeeded,floorRetail,marketPpg,benchmark,marketTarget,rawRecommended,recommended,wholesale,netRevenue,profit,actualGm}}
const pageMeta={dashboard:['ภาพรวมตลาด','เห็นราคา คู่แข่ง และโอกาสในหน้าเดียว'],competitors:['สำรวจคู่แข่ง','เก็บข้อมูลหน้าร้านและออนไลน์อย่างเป็นระบบ'],pricing:['ตั้งราคาเพื่อแข่งขัน','คำนวณจากต้นทุนจริง เงื่อนไขห้าง และราคาตลาด'],analysis:['วิเคราะห์เชิงลึก','ค้นหาช่องว่างและวางแผนตอบโต้คู่แข่ง']};
function switchPage(page){qsa('.page').forEach(x=>x.classList.remove('active'));qs('#'+page+'Page').classList.add('active');qsa('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));qs('#pageTitle').textContent=pageMeta[page][0];qs('#pageSubtitle').textContent=pageMeta[page][1];qs('#addBtn').style.display=page==='competitors'?'inline-flex':'none';renderAll()}
qsa('[data-page]').forEach(b=>b.addEventListener('click',()=>switchPage(b.dataset.page)));
function scoreDots(v){return `<span class="score">${[1,2,3,4,5].map(i=>`<i class="${i<=v?'on':''}"></i>`).join('')}</span>`}
function positionTag(c){const r=normalized(c),m=avg(state.competitors.filter(x=>x.weight&&usedPrice(x)>0).map(x=>normalized(x)));return r<m*.9?'<span class="tag value">ประหยัด</span>':r>m*1.1?'<span class="tag premium">พรีเมียม</span>':'<span class="tag">กลาง</span>'}
function renderDashboard(){const cp=state.competitors.filter(c=>c.weight&&usedPrice(c)>0),pricing=calcPricing();const prices=cp.map(usedPrice),norms=cp.map(c=>normalized(c));const direct=cp.filter(c=>c.type==='คู่แข่งตรง').length;const kpis=[['คู่แข่งในฐานข้อมูล',cp.length+' รายการ',direct+' คู่แข่งตรง','rgba(93,213,216,.15)'],['ราคาเฉลี่ยต่อแพ็ก',money(avg(prices)),'ราคากลาง '+money(median(prices)),'rgba(110,181,255,.15)'],['ราคาเทียบ '+state.pricing.productWeight+' กรัม',money(avg(norms)),'ช่วง '+money(Math.min(...norms))+' – '+money(Math.max(...norms)),'rgba(232,184,87,.15)'],['ราคาแนะนำ',money(pricing.recommended),'Floor '+money(pricing.floorRetail),'rgba(85,214,158,.15)']];qs('#kpiCards').innerHTML=kpis.map(x=>`<div class="card kpi" style="--accent:${x[3]}"><div class="kpi-label">${x[0]}</div><div class="kpi-value">${x[1]}</div><div class="kpi-note">${x[2]}</div></div>`).join('');qs('#chartWeight').textContent=state.pricing.productWeight+' กรัม';renderChart(cp);renderInsights(cp,pricing)}
function renderChart(cp){const el=qs('#priceChart');if(!cp.length){el.innerHTML='<div class="empty">ยังไม่มีข้อมูล</div>';return}const data=[...cp].sort((a,b)=>normalized(b)-normalized(a)).slice(0,8),max=Math.max(...data.map(c=>normalized(c)),1),W=780,H=280,left=105,right=35,top=16,bottom=30,innerW=W-left-right,innerH=H-top-bottom,rowH=innerH/data.length;let grid='';for(let i=0;i<=4;i++){const x=left+innerW*i/4;grid+=`<line class="chart-grid" x1="${x}" y1="${top}" x2="${x}" y2="${H-bottom}"/><text class="chart-label" x="${x}" y="${H-7}" text-anchor="middle">${Math.round(max*i/4)}</text>`}const bars=data.map((c,i)=>{const y=top+i*rowH+5,h=Math.max(rowH-10,10),w=innerW*normalized(c)/max;return `<text class="chart-label" x="${left-8}" y="${y+h/2+4}" text-anchor="end">${escapeHtml(c.brand).slice(0,15)}</text><rect class="bar" x="${left}" y="${y}" width="${w}" height="${h}"><title>${c.brand}: ${money(normalized(c))}</title></rect><text class="chart-label" x="${left+w+7}" y="${y+h/2+4}">${money(normalized(c))}</text>`}).join('');el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="barGradient" x1="0" x2="1"><stop offset="0" stop-color="#5dd5d8"/><stop offset="1" stop-color="#e8b857"/></linearGradient></defs>${grid}${bars}</svg>`}
function renderInsights(cp,pricing){if(!cp.length)return;const cheapest=[...cp].sort((a,b)=>normalized(a)-normalized(b))[0],strongest=[...cp].sort((a,b)=>(b.packScore+b.productScore+b.diffScore)-(a.packScore+a.productScore+a.diffScore))[0],avgNorm=avg(cp.map(c=>normalized(c))),position=pricing.recommended/avgNorm;const insights=[['คู่แข่งราคาต่ำ',`${cheapest.brand} อยู่ที่ ${money(normalized(cheapest))} เมื่อเทียบ ${state.pricing.productWeight} กรัม ไม่จำเป็นต้องไล่ราคาหากกำไรไม่พอ`],['คู่แข่งแข็งแรง',`${strongest.brand} ได้คะแนนรวม ${strongest.packScore+strongest.productScore+strongest.diffScore}/15 ควรศึกษาการสื่อสารและแพ็กเกจ`],['สุขภาพราคา',`ราคาขั้นต่ำที่ยังรักษากำไรเป้าคือ ${money(pricing.floorRetail)} และราคาตลาดเฉลี่ยคือ ${money(avgNorm)}`]];qs('#insightList').innerHTML=insights.map(x=>`<div class="insight"><span class="insight-dot"></span><div><strong>${x[0]}</strong><p>${x[1]}</p></div></div>`).join('');let title,text,pill;if(position<.92){title='กลยุทธ์: เจาะตลาดด้วยความคุ้มค่า';text='ราคาของเราต่ำกว่าตลาดชัด ควรใช้เป็น Trial Pack หรือจุดซื้อทดลอง แต่อย่าลดจนภาพลักษณ์เสีย';pill='VALUE'}else if(position<=1.1){title='กลยุทธ์: แข่งขันตรงตลาด';text='ราคาอยู่ในช่วงที่ลูกค้าคุ้นเคย ให้ชนะด้วยรูปแบบปลาหวานเสียบไม้ แพ็กที่เด่น และรสชาติชัด';pill='MARKET FIT'}else{title='กลยุทธ์: พรีเมียมแบบมีเหตุผล';text='ราคาสูงกว่าตลาด ต้องมีคุณภาพ เนื้อปลา เรื่องราว และแพ็กเกจที่ลูกค้าเห็นคุณค่าได้ทันที';pill='PREMIUM'}qs('#strategyTitle').textContent=title;qs('#strategyText').textContent=text;qs('#strategyPill').textContent=pill}
