const competitorFields=[['brand','แบรนด์','text',''],['product','ชื่อสินค้า / รสชาติ','text','wide'],['channel','ช่องทาง / ร้าน','text',''],['type','ประเภทคู่แข่ง','select',''],['weight','น้ำหนักสุทธิ','number',''],['normalPrice','ราคาปกติ','number',''],['promoPrice','ราคาโปรโมชั่น','number',''],['packScore','คะแนนแพ็กเกจ','selectScore',''],['productScore','คะแนนสินค้า','selectScore',''],['diffScore','คะแนนความแตกต่าง','selectScore',''],['shelf','ตำแหน่งชั้น','text',''],['url','URL แหล่งข้อมูล','url','wide'],['sellingPoint','จุดขาย / คำเคลม','textarea','wide'],['note','จุดอ่อน / ข้อสังเกต','textarea','full']];
function buildCompetitorForm(c={}){qs('#competitorFormFields').innerHTML=competitorFields.map(([k,l,t,cls])=>{let input;if(t==='select')input=`<select class="input" name="${k}"><option ${c[k]==='คู่แข่งตรง'?'selected':''}>คู่แข่งตรง</option><option ${c[k]==='หมวดเดียวกัน'||!c[k]?'selected':''}>หมวดเดียวกัน</option><option ${c[k]==='คู่แข่งทางอ้อม'?'selected':''}>คู่แข่งทางอ้อม</option></select>`;else if(t==='selectScore')input=`<select class="input" name="${k}">${[1,2,3,4,5].map(v=>`<option value="${v}" ${num(c[k]||3)===v?'selected':''}>${v} / 5</option>`).join('')}</select>`;else if(t==='textarea')input=`<textarea class="input" name="${k}">${escapeHtml(c[k]||'')}</textarea>`;else input=`<input class="input" name="${k}" type="${t}" step="0.01" value="${escapeAttr(c[k]??'')}">`;return `<div class="form-group ${cls}"><label>${l}</label>${input}</div>`}).join('')}
function openModal(id=null){editingId=id;const c=id?state.competitors.find(x=>x.id===id):{};qs('#modalTitle').textContent=id?'แก้ไขข้อมูลคู่แข่ง':'เพิ่มข้อมูลคู่แข่ง';buildCompetitorForm(c);qs('#modalBackdrop').classList.add('open')}
function closeModal(){qs('#modalBackdrop').classList.remove('open');editingId=null}window.openModal=openModal;
function removeCompetitor(id){if(!confirm('ลบข้อมูลคู่แข่งรายการนี้?'))return;state.competitors=state.competitors.filter(c=>c.id!==id);saveState();renderAll();toast('ลบข้อมูลแล้ว')}window.removeCompetitor=removeCompetitor;
qs('#competitorForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),obj=Object.fromEntries(fd.entries());['weight','normalPrice','promoPrice','packScore','productScore','diffScore'].forEach(k=>obj[k]=num(obj[k]));if(!obj.brand||!obj.product||!obj.weight||!obj.normalPrice){toast('กรอกแบรนด์ สินค้า น้ำหนัก และราคาให้ครบ');return}if(editingId){const i=state.competitors.findIndex(c=>c.id===editingId);state.competitors[i]={...state.competitors[i],...obj}}else state.competitors.unshift({id:'c'+Date.now(),...obj});saveState();closeModal();renderAll();toast('บันทึกข้อมูลแล้ว')});
qs('#addBtn').addEventListener('click',()=>openModal());qs('#closeModal').addEventListener('click',closeModal);qs('#cancelModal').addEventListener('click',closeModal);qs('#modalBackdrop').addEventListener('click',e=>{if(e.target===qs('#modalBackdrop'))closeModal()});['searchInput','channelFilter','typeFilter'].forEach(id=>qs('#'+id).addEventListener(id==='searchInput'?'input':'change',renderCompetitors));
qs('#exportBtn').addEventListener('click',()=>download('chawchaosamut-competitor-data.json',JSON.stringify(state,null,2),'application/json'));qs('#importBtn').addEventListener('click',()=>qs('#importFile').click());qs('#importFile').addEventListener('change',async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!Array.isArray(d.competitors))throw Error();state={competitors:d.competitors,pricing:{...defaultPricing,...d.pricing}};saveState();renderAll();toast('นำเข้าข้อมูลสำเร็จ')}catch(err){toast('ไฟล์ข้อมูลไม่ถูกต้อง')}e.target.value=''});qs('#csvBtn').addEventListener('click',()=>{const h=['แบรนด์','สินค้า','ช่องทาง','ประเภท','น้ำหนัก','ราคาปกติ','ราคาโปร','ราคาที่ใช้','บาทต่อกรัม','ราคาเทียบน้ำหนักเรา','จุดขาย','ข้อสังเกต'];const rows=state.competitors.map(c=>[c.brand,c.product,c.channel,c.type,c.weight,c.normalPrice,c.promoPrice,usedPrice(c),ppg(c).toFixed(2),normalized(c).toFixed(2),c.sellingPoint,c.note]);download('competitor-survey.csv','\ufeff'+[h,...rows].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv')});
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function toast(t){const el=qs('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}function escapeAttr(s){return escapeHtml(s).replace(/'/g,'&#39;')}
function renderAll(){renderDashboard();renderCompetitors();if(!qs('#pricingForm').children.length)renderPricingForms();else renderPricingResults();renderAnalysis()}
renderAll();switchPage('dashboard');
